### ISSUE TITLE
ReclaimPolicy not work as expected, Request useOnlyPVCName to be able to remount same pv content over gpfs

### ISSUE THREAD

**Issue by sinonkt** [kubevirt/hostpath-provisioner#44]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/kind enhancement

Hi!, First of all thank you for crafting pretty neat provisioner/operator, that's exactly what i'm looking for!.
 
My use cases is to have dynamic provisioning over gpfs via simple hostpath style, that every node already have the same mount point, which look something like this project.
https://github.com/torchbox/k8s-hostpath-provisioner

and only 2 things needed to be solved to have this features!.
**What happened**:
1. [Bug] ReclaimPolicy not work as expected, provisioner still create pv with ReclaimPolicy `Delete` even StorageClass was set as `Retain` which led to my pv content on gpfs was delete everytime.
![reclaimPolicy_not_working_as_expected](https://user-images.githubusercontent.com/13428859/77795984-10ac6300-70a1-11ea-8f11-53ea6bc7d45a.jpg)
2. [Echancement] has `useOnlyPVCName` flag, to have consistent pv naming without hashed, when we needed to mount on the same mount path on gpfs. so that same pvc name can point to same path on gpfs when comes to HA via just nfs hostpath.
![enhancement](https://user-images.githubusercontent.com/13428859/77795977-0db17280-70a1-11ea-9c97-9fa491eefb35.png)

**What you expected to happen**:
1. PV was created with correct ReclaimPolicy. (Retain)
2. Have option to have pv path base on only pvc name when we need consistent naming

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f ../../hostpath-provisioner-operator/deploy/operator.yaml -n hostpath-provisioner
kubectl apply -f ./hostpathprovisioner_cr.yaml -n hostpath-provisioner 
```
apiVersion: hostpathprovisioner.kubevirt.io/v1alpha1
kind: HostPathProvisioner
metadata:
  name: gpfs-based-hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  pathConfig:
    path: "/nbt_data/k8s/pvs" #The path of the directory on the node
    useNamingPrefix: "true" #Use the name of the PVC bound to the created PV as part of the directory name.
```
kubectl apply -f ./storageclass-gpfs.yaml -n hostpath-provisioner
from deploy/test dir with this StorageClass
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gpfs
provisioner: kubevirt.io/hostpath-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```
then create PVC that look something like these
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  storageClassName: gpfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
```
**Anything else we need to know?**:
I'm really new to k8s operator concept, provisioner and also open source community. please advices me if there any :))
I review a little bit on ibm-storage-enabler when comes to provisioning on gpfs
but it's not straightforward but sure to be suitable way to provision. so we decided to go with your style for a while which promising and robust one :).
https://github.com/IBM/ubiquity-k8s

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.16.6
- Cloud provider or hardware configuration:
On-premise k8s
- Install tools:
- Others:
